src/blog/urls.py
from django.urls import path
from . import views

app_name = "blog"

urlpatterns = [
    # url('', views.PostListView.as_view(), name='post_list'),
    path('', views.post_list, name='post_list'),
    path('tag/<slug:tag_slug>/', views.post_list, name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/', views.post_detail, name='post_detail'),
    path('<int:post_id>/share/', views.post_share, name='post_share'),
]

src/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.contrib.sitemaps.views import sitemap
from blog.sitemaps import PostSitemap

sitemaps = {
'posts': PostSitemap,
}

urlpatterns = [
    path('admin/', admin.site.urls),
    path('blog/', include('blog.urls', namespace="blog")),
    path('sitemap.xml/', sitemap, {'sitemaps': sitemaps}, name='django.contrib.sitemaps.views.sitemap'),
]

src/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse

from taggit.managers import TaggableManager

# Create your models here.

# We are going to create a custom manager to retrieve all posts with published status.
# -----------------------------------------
class PublishedManager(models.Manager):
    def get_queryset(self): # Is the method that returns the QuerySet to be executed.
        return super(PublishedManager, self).get_queryset().filter(status='published') # We can retrieve all published posts.

# Model Post 
# -----------------------------------------
class Post(models.Model):
    STATUS_CHOICES = (
        ( "draft", "Draft" ),
        ( "published", "Published" ),
    )
    title = models.CharField( max_length=120 )
    slug = models.SlugField( max_length=250, unique_for_date="publish" ) # This way we ensure that there will be only one post with a slug for a given date
    author = models.ForeignKey( User, related_name="blog_posts", on_delete=models.CASCADE )
    body = models.TextField()
    publish = models.DateTimeField(default=timezone.now) # This is just a timezone-aware datetime.now by default.
    created = models.DateTimeField(auto_now_add=True) # The date will be saved automatically when creating an object.
    updated = models.DateTimeField(auto_now=True) # The date will be updated automatically when saving an object..
    status = models.CharField( max_length=10, choices=STATUS_CHOICES, default="draft" )

    objects = models.Manager() # The default manager.
    published = PublishedManager() # Our custom manager.
    tags = TaggableManager() # Third-party Django

    class Meta:
        ordering = ( "-publish", )

    def __str__(self):
        return f"{self.id} : {self.title} by {self.author}"

    def get_absolute_url(self):
        return reverse('blog:post_detail', args=[self.publish.year,
                                                    self.publish.month,
                                                    self.publish.day,
                                                    self.slug])


class Comment(models.Model): 
    post = models.ForeignKey(Post, related_name='comments', on_delete=models.CASCADE)
    name = models.CharField(max_length=80) 
    email = models.EmailField() 
    body = models.TextField() 
    created = models.DateTimeField(auto_now_add=True) 
    updated = models.DateTimeField(auto_now=True) 
    active = models.BooleanField(default=True) 
 
    class Meta: 
        ordering = ( 'created', ) 
 
    def __str__(self): 
        return f'Comment by {self.name} on {self.post}'

src/blog/forms.py
from django import forms
from .models import Comment

class EmailPostForm(forms.Form):
    name = forms.CharField(max_length=25)
    email = forms.EmailField()
    to = forms.EmailField()
    comments = forms.CharField(required=False, widget=forms.Textarea)


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = [ "name", "email", "body" ]

src/blog/views.py
from django.shortcuts import render, get_object_or_404
from django.core.mail import send_mail
from django.db.models import Count

from taggit.models import Tag

from .models import Post, Comment
from .forms import EmailPostForm, CommentForm
# Create your views here.

def post_list(request, tag_slug=None):
    object_list = Post.published.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    return render(request, 'blog/post/list.html', { "posts": object_list, "tag": tag })


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post, 
                                    status='published',
                                    publish__year=year,
                                    publish__month=month,
                                    publish__day=day)
    return render(request, 'blog/post/detail.html', {'post': post})


# class PostListView(ListView):
#     queryset = Post.published.all() # model = Post and Djangowould have built the generic Post.objects.all().
#     context_object_name = 'posts' # The default variable is object_list if we don't specify any context_object_name.
#     template_name = 'blog/post/list.html' # ListView will use blog/post_list.html .


def post_share(request, post_id):
    # Retrieve post by id
    post = get_object_or_404(Post, id=post_id, status='published')
    sent = False 
 
    if request.method == 'POST':
        # Form was submitted
        form = EmailPostForm(request.POST)
        if form.is_valid():
            # Form fields passed validation
            cd = form.cleaned_data
            post_url = request.build_absolute_uri( post.get_absolute_url() )
            subject = f'{cd["name"]} ({cd["email"]}) recommends you reading \"{post.title}\"'
            message = f'Read "{post.title}" at {post_url}\n\n{cd["name"]}\'s comments: {cd["comments"]}'
            send_mail(subject, message, cd['email'], [cd['to']])
            sent = True
    else:
        form = EmailPostForm()
    return render(request, 'blog/post/share.html', {'post': post, 'form': form, 'sent': sent})


def post_detail(request, year, month, day, post):
    post = get_object_or_404(Post, slug=post,
        status='published',
        publish__year=year,
        publish__month=month,
        publish__day=day)

    # List of active comments for this post
    comments = post.comments.filter(active=True) # We are using the manager for related objects we defined as comments using the related_name attribute of the relationship in the Comment model.
    if request.method == "POST":
        # A comment was posted
        comment_form = CommentForm(data=request.POST)
        if comment_form.is_valid():
            # Create Comment object but don't save to database yet
            new_comment = comment_form.save(commit=False)
            # Assign the current post to the comment
            new_comment.post = post
            # Save the comment to the database
            new_comment.save()
    else:
        comment_form = CommentForm()
    # List of similar posts
    post_tags_ids = post.tags.values_list('id', flat=True)
    similar_posts = Post.published.filter(tags__in=post_tags_ids).exclude(id=post.id)
    similar_posts = similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:4]
    return render(request, 'blog/post/detail.html', { "post": post, 
        "comments": comments, 
        "comment_form": comment_form,
        'similar_posts': similar_posts, })

src/blog/templates/blog/base.html
{% load staticfiles %}
<!DOCTYPE html>
<html>
    <head>
        <title>
            {% block title %}
            {% endblock title %}
        </title>
        <link href="{% static 'css/blog.css' %}" rel="stylesheet">
    </head>
    <body>
        <div id="content">
            {% block content %}
            {% endblock content %}
        </div>
        <div id="sidebar">
            <h2>My blog</h2>
            <p>This is my blog.</p>
        </div>
    </body>
</html>

src/blog/templates/blog/post/detail.html
{% extends "blog/base.html" %}

{% block title %}
    {{ post.title }}
{% endblock %}
{% block content %}
    <h1>{{ post.title }}</h1>
    <p class="tags">Tags: {{ post.tags.all|join:", " }}</p>
    <p class="date">
        Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|linebreaks }}
    <p>
        <a href="{% url 'blog:post_share' post.id %}">
            Share this post
        </a>
    </p>
    {% with comments.count as total_comments %}
        <h2>
        {{ total_comments }} comment{{ total_comments|pluralize }}
        </h2>
    {% endwith %}
    {% for comment in comments %}
        <div class="comment">
            <p class="info">
                Comment {{ forloop.counter }} by {{ comment.name }}
                {{ comment.created }}
            </p>
            {{ comment.body|linebreaks }}
        </div>
            {% empty %}
        <p>There are no comments yet.</p>
    {% endfor %}
    <h2>Similar posts</h2>
    {% for post in similar_posts %}
        <p>
            <a href="{{ post.get_absolute_url }}">{{ post.title }}</a>
        </p>
    {% empty %}
    There are no similar posts yet.
    {% endfor %}
    {% if new_comment %}
        <h2>Your comment has been added.</h2>
    {% else %}
        <h2>Add a new comment</h2>
        <form action="." method="post">
            {% csrf_token %}
            {{ comment_form.as_p }}
            <p><input type="submit" value="Add comment"></p>
        </form>
    {% endif %}
{% endblock %}

src/blog/templates/blog/post/list.html
{% extends "blog/base.html" %}
 
{% block title %}My Blog{% endblock %}
 
{% block content %}
  <h1>My Blog</h1>
  {% if tag %}
    <h2>Posts tagged with "{{ tag.name }}"</h2>
  {% endif %}
  {% for post in posts %}
    <h2>
      <a href="{{ post.get_absolute_url }}">
        {{ post.title }}
      </a>
    </h2>
    <p class="tags">
      Tags:
      {% for tag in post.tags.all %}
        <a href="{% url "blog:post_list_by_tag" tag.slug %}">
          {{ tag.name }}
        </a>
        {% if not forloop.last %}, {% endif %}
      {% endfor %}
    </p>
    <p class="date">
      Published {{ post.publish }} by {{ post.author }}
    </p>
    {{ post.body|truncatewords:30|linebreaks }}
  {% endfor %}
{% endblock %}

src/blog/templates/blog/post/share.html
{% extends "blog/base.html" %}

{% block title %}Share a post{% endblock %}

{% block content %}
    {% if sent %}
        <h1>E-mail successfully sent</h1>
        <p>
            "{{ post.title }}" was successfully sent to {{ form.cleaned_data.to }}.
        </p>
    {% else %}
        <h1>Share "{{ post.title }}" by e-mail</h1>
        <form action="." method="POST">
            {% csrf_token %}
            {{ form.as_p }}
            <input type="submit" value="Send e-mail">
        </form>
    {% endif %}
{% endblock %}